apiVersion: v1
kind: Service
metadata:
  name: fastapi
  namespace: tracing

spec:
  selector:
    app: fastapi

  ports:
    - port: 8000
      targetPort: 8000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
  namespace: tracing

spec:
  replicas: 1

  selector:
    matchLabels:
      app: fastapi

  template:

    metadata:
      labels:
        app: fastapi

    spec:

      containers:

        - name: fastapi

          image: fastapi-tracing:v2

          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8000

          env:

            - name: OTEL_SERVICE_NAME
              value: "fastapi-tracing-demo"

            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://jaeger.tracing.svc.cluster.local:4317"

            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: "grpc"

            - name: OTEL_TRACES_SAMPLER
              value: "always_on"

            - name: OTEL_METRICS_EXPORTER
              value: "none"

            - name: OTEL_LOGS_EXPORTER
              value: "none"